### ISSUE TITLE
Cannot edit without newType param

### ISSUE THREAD

**Issue by ginpei** [ginpei/potoshop#16]
1. Open the path `/`
2. Long tap to start paint
3. You'll see the canvas is invisible

Its style:

```css
element.style {
  transform: translate(684px, 385.5px) scale(0);
}
```
